# Generated by Django 3.2.7 on 2021-09-28 04:21

from django.db import migrations, models
import paint_game.models


class Migration(migrations.Migration):

    dependencies = [
        ('paint_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=paint_game.models.get_name)),
            ],
        ),
    ]
